Binary dict
FreeCourseJava/vv_15_task pull request #1
Opened 2022-10-08 12:47 UTC by ivtcro

2022-10-08 13:27 UTC, blekkiw requested changes

2022-10-08 13:27 UTC, blekkiw commented on src/homework/BinaryDictionary.java
> +            if (branch.key.hashCode() == key.hashCode() && branch.key.equals(key)) {
Интересно, а что будет, если в качестве искомого ключа передать null? (ничего хорошего)

2022-10-08 13:27 UTC, blekkiw commented on src/homework/BinaryDictionary.java
> +                if (key.hashCode() >= branch.key.hashCode()) {
А почему >= ? Ты чуть выше проверяешь на == и equals. Получается, если хэшкоды совпадут, но ключи не будут равны по equals мы почему-то пойдем в правую ветку. Так же можно и не найти что искали

2022-10-08 13:27 UTC, blekkiw commented on src/homework/BinaryDictionary.java
> +                } else if (key.hashCode() >= branch.key.hashCode()) {
Та же странность что и выше. При этом прикол в том, что если хэши совапдают и объекты идентичны по equals - то мы кинем ошибку, а если не идентичны по equals то перезатрем какое-то значение в правой ноде (хотя хэши будут совпадать)

2022-10-08 13:27 UTC, blekkiw commented on src/homework/BinaryDictionary.java
> +                } else if (key.hashCode() >= branch.key.hashCode()) {
Ошибку кстати лучше кидать, чем тихо в err печатать

2022-10-08 13:27 UTC, blekkiw commented on src/homework/BinaryDictionary.java
> +        if (res.size() > 0) {
Можно и нужно использовать метод isEmpty()

2022-10-08 13:27 UTC, blekkiw commented on src/homework/BinaryDictionary.java
> +            return null;
Соверешнно не логично. Если список пуст, возвращаем null. В итоге пользователям твоего класса, нужно будет снаружи всегда проверять на null, прежде чем использовать что ты отдал. Намного лучше отдать просто пустой список.

2022-10-08 13:27 UTC, blekkiw commented on src/homework/BinaryDictionary.java
> +            {
Тут похоже забыт конструктор. Так лучше не писать. 
Объяснение: https://rules.sonarsource.com/java/tag/pitfall/RSPEC-1171

2022-10-08 13:27 UTC, blekkiw commented on src/homework/BinaryDictionary.java
> +        return new Iterator<>() {
Видимо использовалась джава отличная от 8. На 8 этот код не компилируется, а на 11 уже да

2022-10-08 15:45 UTC, ivtcro commented on src/homework/BinaryDictionary.java
> +            if (branch.key.hashCode() == key.hashCode() && branch.key.equals(key)) {
ничего хорошего ) поправлю

2022-10-08 15:57 UTC, ivtcro commented on src/homework/BinaryDictionary.java
> +                } else if (key.hashCode() >= branch.key.hashCode()) {
если ключи равны по хэшу, но не равны по значению то ничего не должно перезатираться - идём дальше по дереву, пока не найдем пустое место для вставки.

по поводу ошибки - думал над тем что кидать exception, но решил, что так как метод ничего не возвращает, то при дизайне посчитали что результат операции не важен
но в stderr всё равно решил выдать сообщение - не ошибка, но warning

2022-10-08 16:03 UTC, ivtcro commented on src/homework/BinaryDictionary.java
> +            {
Как я понял, анонимные классы не могут иметь конструкторы
https://docs.oracle.com/javase/tutorial/java/javaOO/anonymousclasses.html
"However, you cannot declare constructors in an anonymous class."

2022-10-08 16:07 UTC, ivtcro commented on src/homework/BinaryDictionary.java
> +        if (res.size() > 0) {
заменю

2022-10-08 16:10 UTC, ivtcro commented on src/homework/BinaryDictionary.java
> +            return null;
да, согласен
тогда и предыдущая проверка не нужна

2022-10-08 16:24 UTC, ivtcro commented on src/homework/BinaryDictionary.java
> +                } else if (key.hashCode() >= branch.key.hashCode()) {
закоммитил TestBinaryDict.java с новыми проверками
коллизию хэшей отрабатывает

2022-10-08 16:24 UTC, ivtcro commented on src/homework/BinaryDictionary.java
> +                if (key.hashCode() >= branch.key.hashCode()) {
куда-то же нужно вставить такие значение
если принять что ключи с одиаковым хэшом всегда идут вправо - и для get и для put - то кажется должно работать, 
но протестирую

2022-10-08 16:25 UTC, ivtcro commented on src/homework/BinaryDictionary.java
> +                if (key.hashCode() >= branch.key.hashCode()) {
закоммитил TestBinaryDict.java с новыми проверками
коллизию хэшей отрабатывает

2022-10-08 16:36 UTC, ivtcro commented on src/homework/BinaryDictionary.java
> +        return new Iterator<>() {
17-ая java

2022-10-12 08:56 UTC, blekkiw approved these changes

2022-10-22 08:58 UTC, merged